exports
  JNI_OnLoad name 'JNI_OnLoad',
  JNI_OnUnload name 'JNI_OnUnload',
  bsNativeInit name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeInit',
  bsNativeOnViewCreated name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeOnViewCreated',
  bsNativeOnViewChanged name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeOnViewChanged',
  bsNativeOnDraw name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeOnDraw',
  bsNativeOnChangeFocus name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeOnChangeFocus',
  bsNativeOnTouch name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeOnTouch',
  bsNativeOnKeyDown name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeOnKeyDown',
  bsNativeOnKeyUp name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeOnKeyUp',
  bsNativeNextAction name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeNextAction',
  bsNativeOnBackPressed name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeOnBackPressed',
  bsNativeGetIntAttribute name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeGetIntAttribute',
  bsNativeGetBoolAttribute name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeGetBoolAttribute',
  bsNativeOnViewDestroy name 'Java_org_bshark_blackshark_BlackSharkApplication_bsNativeOnViewDestroy'
;
